<?php
// car_history.php — Line 3 colour scheme applied to the live page.
//
// FIX (the "Cannot reinitialise DataTable" error):
//   Removed the extra  $('#add_form').DataTable(...)  block at the bottom.
//   Your template (custom.min.js / additional.js) already auto-initialises
//   .datatable2 tables, so that second init on the same table was the cause.
//   One init only now.
//
// Two more things restored after the merge:
//   * $dateClause block (your union query references it — it was undefined).
//   * Problem Type uses getProblemType($db,$row['incident_type']) again;
//     echoing $row['problem_type'] was a sample-data leftover and would
//     render that column blank against your real query.
//
// The only thing that restyles the page is the <style> block below.

	$db=new mysqli("localhost","psssilva","!D40nkC2azXg$","is_transport");


	$db2=new mysqli("localhost","psssilva","!D40nkC2azXg$","is_transport_old");


$car_id=$_GET['car_id'];

$dateClause="";

if(isset($_GET['m'])){
	$dateClause=" and incident_date like '".$_GET['y']."-".date("m",strtotime($_GET['y']."-".$_GET['m']."-01"))."%%' ";
	$dateClause2=" and transport_old.incident_date like '".$_GET['y']."-".date("m",strtotime($_GET['y']."-".$_GET['m']."-01"))."%%' ";
}
else {
	if(isset($_GET['y'])){
		$dateClause=" and incident_date like '".$_GET['y']."-%%' ";
		$dateClause2=" and transport_old.incident_date like '".$_GET['y']."-".date("m",strtotime($_GET['y']."-".$_GET['m']."-01"))."%%' ";
	}
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Car #<?php echo $car_id; ?> &mdash; Incident History</title>

<link href="css/font-awesome.min.css" rel="stylesheet">
	<link href="css/bootstrap.min.css" rel="stylesheet" />
	<link href="css/bootstrap-responsive.min.css" rel="stylesheet" />
	<link href="css/style.min.css" rel="stylesheet" />
	<link href="css/style-responsive.min.css" rel="stylesheet" />
	<link href="css/retina.css" rel="stylesheet" />
	<link rel="stylesheet" type="text/css" href="css/dataTables.tableTools.css">
<style type="text/css">
/* ===========================================================================
   LINE 3 SCHEME (corrected)
   The only block that restyles the page. Blue leads the structure; yellow is
   a small accent (3px brand stripe under the title bar + the current page
   button), never the gridlines.
   =========================================================================== */

body { margin-left:30px; margin-right:30px; background:#FAFAF6; color:#1A2238; }

h2 { color:#1A2238; }

/* search / length / info controls (generated by DataTables) */
#add_form_wrapper .dataTables_length,
#add_form_wrapper .dataTables_filter { color:#1A2238; }
#add_form_wrapper .dataTables_info    { color:#5A6275; }
#add_form_wrapper .dataTables_length select,
#add_form_wrapper .dataTables_filter input {
    border:1px solid #D8D2C2; background:#FFFFFF; color:#1A2238;
    border-radius:5px; padding:4px 8px;
}

/* table grid — calm warm-neutral, replacing the old bright gold border */
#add_form { background:#FFFFFF; }
#add_form th, #add_form td { border:1px solid #E5DECC !important; }

/* title bar (the colspan row) — blue, with a 3px yellow brand stripe */
#add_form thead tr:first-child th {
    background:#00529B !important; color:#FFFFFF !important;
    border:1px solid #00529B !important;
    border-bottom:3px solid #FDB813 !important;
    text-align:center; padding:10px; font-weight:500;
	  position: sticky;
  top: 0;
    z-index:2;
}

/* column headers — light neutral; blue underline ties them to the bar */
#add_form thead tr:nth-child(2) th {
    background:#F1EEE3 !important; color:#1A2238 !important;
    border-bottom:2px solid #00529B !important;
    text-align:left; padding:8px 10px; font-weight:500;
		  position: sticky;
		    top: 40px;
			  z-index: 1;


}

/* body cells + soft zebra striping (warm grey, not yellow) */
#add_form tbody td                    { background:#FFFFFF !important; padding:8px 10px; vertical-align:top; }
#add_form tbody tr:nth-child(even) td  { background:#F5F2E8 !important; }

/* incident-number links */
#add_form a       { color:#00529B; }
#add_form a:hover { color:#003E76; }

/* pagination — neutral, yellow ONLY on the active page */
#add_form_wrapper .dataTables_paginate .paginate_button {
    border:1px solid #E5DECC !important; background:#FFFFFF !important;
    color:#1A2238 !important; border-radius:0;
}
#add_form_wrapper .dataTables_paginate .paginate_button.current,
#add_form_wrapper .dataTables_paginate .paginate_button.current:hover {
    background:#FDB813 !important; color:#3A2D00 !important; border-color:#FDB813 !important;
}
#add_form_wrapper .dataTables_paginate .paginate_button.disabled,
#add_form_wrapper .dataTables_paginate .paginate_button.disabled:hover {
    color:#9A9384 !important; background:#FFFFFF !important;
}
/* ====================== end LINE 3 SCHEME ================================== */
</style>
</head>
<body>

<div align="center">
<h2 style="font-size:28px; font-weight:bold;">Car #<?php echo $car_id; ?></h2>
</div>
<br>
<br>
Incident History
<br>
<table class="table table-striped table-bordered bootstrap-datatable datatable2" width="80%" id="add_form" name="add_form">
    <thead>
    <tr>
        <th colspan="9"><div align="center">Car #<?php echo $car_id; ?></div></th>
    </tr>
    <tr>
        <th>Index No</th>
        <th>Incident Date</th>
        <th>Time of Incident</th>
        <th>Time Resolved</th>
        <th>Duration</th>
        <th>Problem Type</th>
        <th>Equipment</th>

        <th>Incident Number</th>
        <th>Description</th>
    </tr>
    </thead>
    <tbody>
<?php
$sql="(select * from incident_cars inner join incident_union on incident_cars.incident_id=incident_union.id where incident_cars.car_no*1='".$car_id."' ".$dateClause." order by incident_date desc)";

$sql.=" union ";

$sql.="(select * from is_transport_old.incident_cars inner join is_transport_old.incident_union on is_transport_old.incident_cars.incident_id=is_transport_old.incident_union.id where is_transport_old.incident_cars.car_no*1='".$car_id."' ".$dateClause." order by incident_date desc)";
$rs=$db->query($sql);
$nm=$rs->num_rows;

for($i=0;$i<$nm;$i++){

	$incident[strtotime($row['incident_date'])]['date']=date("Y-m-d",strtotime($row['incident_date']));
	$incident[strtotime($row['incident_date'])]['time']=date("H:iA",strtotime($row['incident_date']));

	$incident[strtotime($row['incident_date'])]['duration']=$row['duration'];
	$incident[strtotime($row['incident_date'])]['index_no']=$row['index_no'];
	$incident[strtotime($row['incident_date'])]['problem_type']=getProblemType($db,$row['incident_type']);


	$row=$rs->fetch_assoc();
	?>
    <tr>
        <td><?php echo $row['index_no']; ?></td>
        <td><?php echo date("Y-m-d", strtotime($row['incident_date'])); ?></td>
        <td><?php echo date("H:iA", strtotime($row['incident_date'])); ?></td>
        <td>&nbsp;</td>
        <td><?php echo $row['duration']; ?></td>
        <td><?php echo getProblemType($db,$row['incident_type']); ?></td>
        <td><?php echo getEquipmentType($db,$row['equipt']); ?></td>

        <td><a href='#' onclick='window.open("edit_ccdr.php?ir=<?php echo $row['id']; ?>")'><?php echo $row['incident_no']; ?></a></td>
        <td><?php echo $row['description']; ?></td>
    </tr>
<?php } ?>
    </tbody>
</table>

		<script src="js/jquery-1.10.2.min.js"></script>
		<script src="js/jquery-migrate-1.2.1.min.js"></script>	
		<script src="js/jquery-ui-1.10.3.custom.min.js"></script>	
		<script src="js/jquery.ui.touch-punch.js"></script>	
		<script src="js/modernizr.js"></script>	
		<script src="js/bootstrap.min.js"></script>	
		<script src="js/jquery.cookie.js"></script>	
		<script src='js/fullcalendar.min.js'></script>	
		<script src='js/jquery.dataTables.min.js'></script>
		<script src="js/dataTables.tableTools.js"></script>
			
		<script src="js/excanvas.js"></script>
		<script src="js/jquery.flot.js"></script>
		<script src="js/jquery.flot.pie.js"></script>
		<script src="js/jquery.flot.stack.js"></script>
		<script src="js/jquery.flot.resize.min.js"></script>
		<script src="js/jquery.flot.time.js"></script>
		
		<script src="js/jquery.chosen.min.js"></script>	
		<script src="js/jquery.uniform.min.js"></script>		
		<script src="js/jquery.cleditor.min.js"></script>	
		<script src="js/jquery.noty.js"></script>	
		<script src="js/jquery.elfinder.min.js"></script>	
		<script src="js/jquery.raty.min.js"></script>	
		<script src="js/jquery.iphone.toggle.js"></script>	
		<script src="js/jquery.uploadify-3.1.min.js"></script>	
		<script src="js/jquery.gritter.min.js"></script>	
		<script src="js/jquery.imagesloaded.js"></script>	
		<script src="js/jquery.masonry.min.js"></script>	
		<script src="js/jquery.knob.modified.js"></script>	
		<script src="js/jquery.sparkline.min.js"></script>	
		<script src="js/counter.min.js"></script>	
		<script src="js/raphael.2.1.0.min.js"></script>
		<script src="js/justgage.1.0.1.min.js"></script>	
		<script src="js/jquery.autosize.min.js"></script>	
		<script src="js/retina.js"></script>
		<script src="js/jquery.placeholder.min.js"></script>
		<script src="js/wizard.min.js"></script>
		<script src="js/core.min.js"></script>	
		<script src="js/charts.min.js"></script>	
		<script src="js/custom.min.js"></script>
		<script src="js/additional.js"></script>
<?php
function getProblemType($db,$type){
	$sql="select * from equipment_type where equipment_code='".$type."'";
	$rs=$db->query($sql);

	$nm=$rs->num_rows;
	$row=$rs->fetch_assoc();

	$problem=$row['equipment_name'];
	return $problem;
}
function getEquipmentType($db,$type){
	$sql="select * from equipment where id='".$type."'";
	$rs=$db->query($sql);

	$nm=$rs->num_rows;
	$row=$rs->fetch_assoc();

	$problem=$row['equipment_name'];
	return $problem;
}

?>
</body>
</html>