<?php
	$db=new mysqli("localhost","psssilva","!D40nkC2azXg$","is_transport");
$car_id=$_GET['car_id'];
?>
<link href="css/font-awesome.min.css" rel="stylesheet">
	<link href="css/bootstrap.min.css" rel="stylesheet" />
	<link href="css/bootstrap-responsive.min.css" rel="stylesheet" />
	<link href="css/style.min.css" rel="stylesheet" />
	<link href="css/style-responsive.min.css" rel="stylesheet" />
	<link href="css/retina.css" rel="stylesheet" />
	<link rel="stylesheet" type="text/css" href="css/dataTables.tableTools.css">

	<style type='text/css'>
/*
.rowClass {
	background-color:#eaf2d3;
}

.rowHeading {
	background-color:#a7c942;
	color:rgb(0,51,153);
	color:white;		
}

.train_ava td{
	border: 1px solid #a7c942;
	color: rgb(0,51,153);
	cellpadding: 5px;
}

 .train_ava th {
	border: 1px solid #a7c942;
	cellpadding: 5px;	
}
*/

body {
	margin-left:30px;
	margin-right:30px;

}

/*
input[type="text"]{ 
	height:25px; 
	font-weight:bold; 
	font-size:15px; 
	font-family:courier; 
	border: 1px solid #C6C6C6; 
	background-color: rgb(185, 201, 254);  
	color: rgb(0,51,153);
	border-radius: 3px;
}
*/
/*
#cellHeading {
	background-image: -o-linear-gradient(bottom, rgb(185, 201, 254) 38%, #4ad 62%);
	background-image: -moz-linear-gradient(bottom, rgb(185, 201, 254) 38%,#4ad 62%);
	background-image: -moz-linear-gradient(bottom, rgb(185, 201, 254) 38%, #4ad 62%);
	background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0.38, rgb(185, 201, 254)), color-stop(0.62, #4ad));
	background-image: -webkit-linear-gradient(bottom, rgb(185, 201, 254) 38%,#4ad 62%);
	background-image: -ms-linear-gradient(bottom, rgb(185, 201, 254) 38%, #4ad 62%);
	background-image: linear-gradient(bottom, rgb(185, 201, 254) 38%, #4ad 62%);

	background-color: rgb(185, 201, 254);  

	color: rgb(0,51,153);
	padding:5px;
	-moz-border-radius: 5px;
	border-radius: 5px;

}
*/
/*
input[type="text"]:focus {
	background-color:rgb(158,27,32);

}
textarea:focus {
	background-color:rgb(158,27,32);
	color:white;
	font-weight:bold;

}
.date {
	text-style:bold;
	font-size:20px;

}


textarea{ 
	border: 1px solid rgb(185, 201, 254);
	background-color: rgb(185, 201, 254);  
	color: rgb(0,51,153);
	border-radius: 3px;
}
*/

/* header */
#add_form th{
background-color: #cccccc;
}

#add_form td{
background-color: #F3F3F3;  
border:1px solid #FBCC2A;
}

/*
select { border: 1px solid rgb(185, 201, 254); color: rgb(0,51,153); background-color: rgb(185, 201, 254);  }
*/

</style>
	<style type="text/css">
/* ===========================================================================
   LINE 3 SCHEME (corrected)
   The only block that restyles the page. Blue leads the structure; yellow is
   a small accent (3px brand stripe under the title bar + the current page
   button), never the gridlines.
   =========================================================================== */

body { margin-left:30px; margin-right:30px; background:#FAFAF6; color:#1A2238; }

h2 { color:#1A2238; }

/* search / length / info controls (generated by DataTables) */
#add_form_wrapper .dataTables_length,
#add_form_wrapper .dataTables_filter { color:#1A2238; }
#add_form_wrapper .dataTables_info    { color:#5A6275; }
#add_form_wrapper .dataTables_length select,
#add_form_wrapper .dataTables_filter input {
    border:1px solid #D8D2C2; background:#FFFFFF; color:#1A2238;
    border-radius:5px; padding:4px 8px;
}

/* table grid — calm warm-neutral, replacing the old bright gold border */
#add_form { background:#FFFFFF; }
#add_form th, #add_form td { border:1px solid #E5DECC !important; }

/* title bar (the colspan row) — blue, with a 3px yellow brand stripe */
#add_form thead tr:first-child th {
    background:#00529B !important; color:#FFFFFF !important;
    border:1px solid #00529B !important;
    border-bottom:3px solid #FDB813 !important;
    text-align:center; padding:10px; font-weight:500;
	  position: sticky;
  top: 0;
    z-index:2;
}

/* column headers — light neutral; blue underline ties them to the bar */
#add_form thead tr:nth-child(2) th {
    background:#F1EEE3 !important; color:#1A2238 !important;
    border-bottom:2px solid #00529B !important;
    text-align:left; padding:8px 10px; font-weight:500;
		  position: sticky;
		    top: 40px;
			  z-index: 1;


}

/* body cells + soft zebra striping (warm grey, not yellow) */
#add_form tbody td                    { background:#FFFFFF !important; padding:8px 10px; vertical-align:top; }
#add_form tbody tr:nth-child(even) td  { background:#F5F2E8 !important; }

/* incident-number links */
#add_form a       { color:#00529B; }
#add_form a:hover { color:#003E76; }

/* pagination — neutral, yellow ONLY on the active page */
#add_form_wrapper .dataTables_paginate .paginate_button {
    border:1px solid #E5DECC !important; background:#FFFFFF !important;
    color:#1A2238 !important; border-radius:0;
}
#add_form_wrapper .dataTables_paginate .paginate_button.current,
#add_form_wrapper .dataTables_paginate .paginate_button.current:hover {
    background:#FDB813 !important; color:#3A2D00 !important; border-color:#FDB813 !important;
}
#add_form_wrapper .dataTables_paginate .paginate_button.disabled,
#add_form_wrapper .dataTables_paginate .paginate_button.disabled:hover {
    color:#9A9384 !important; background:#FFFFFF !important;
}
/* ====================== end LINE 3 SCHEME ================================== */
</style>
<?php
/*

#add_form td:last-child{
background-color:white;

}

#add_form td:nth-child(odd) {
background-color: #33aa55; 
color:white;
font-weight:bold;
padding:5px;

}

#add_form td:nth-child(even) {
background-color: rgb(185, 201, 254);  
border:1px solid #4ad;

}
*/
?>
<body>
<br>
Incident History (Others)
<br>
<table class="table table-striped table-bordered bootstrap-datatable datatable2" width=80% id='add_form' name='add_form' >
	<thead>
	<tr>
	<th>Index No</th>
	<th>Incident Date</th>
	<th>Problem Type</th>
	<th>Incident Number</th>
	<th>Description</th>
	</tr>
	</thead>
	<tbody>
<?php

$sql="select * from incident_description inner join incident_report on incident_report.id=incident_description.incident_id where incident_type='others' order by incident_date desc";
$rs=$db->query($sql);
$nm=$rs->num_rows;

for($i=0;$i<$nm;$i++){
	$row=$rs->fetch_assoc();
?>	
	<tr>
		<td><?php echo $row['index_no']; ?></td>
		<td><?php echo "<span>".date("Y-m-d",strtotime($row['incident_date']))."</span>"; ?></td>
		<td><?php echo  getProblemType($db,$row['incident_type']); ?></td>

		<td><a href='#' class='two' onclick='openSlidePanel("edit_ccdr.php?ir=<?php echo  $row['id']; ?>&embed=1","Incident - <?php echo htmlspecialchars($row['incident_no']); ?>")'><?php echo $row['incident_no']; ?></a></td>
</td>
		
		
		
		
		<td><?php echo $row['description']; ?></td>
	
	</tr>
<?php
}
?>	
</tbody>
</table>

<!--
		<script src="js/jquery-1.10.2.min.js"></script>
		<script src="js/jquery-ui-1.10.3.custom.min.js"></script>	
			<script src="js/bootstrap.min.js"></script>	

		<script src="js/jquery-migrate-1.2.1.min.js"></script>	
			<script src="js/jquery.ui.touch-punch.js"></script>	
			<script src="js/modernizr.js"></script>	
			<script src="js/jquery.cookie.js"></script>	
			<script src='js/fullcalendar.min.js'></script>	
			<script src='js/jquery.dataTables.js'></script>
			<script src="js/dataTables.tableTools.js"></script>
			<script src="js/core.min.js"></script>	

			<script src="js/excanvas.js"></script>
		<script src="js/jquery.flot.js"></script>
		<script src="js/jquery.flot.pie.js"></script>
		<script src="js/jquery.flot.stack.js"></script>
		<script src="js/jquery.flot.resize.min.js"></script>
		<script src="js/jquery.flot.time.js"></script>
		
		<script src="js/jquery.chosen.min.js"></script>	
		<script src="js/jquery.uniform.min.js"></script>		
		<script src="js/jquery.cleditor.min.js"></script>	
		<script src="js/jquery.noty.js"></script>	
		<script src="js/jquery.elfinder.min.js"></script>	
		<script src="js/jquery.raty.min.js"></script>	
		<script src="js/jquery.iphone.toggle.js"></script>	
		<script src="js/jquery.uploadify-3.1.min.js"></script>	
		<script src="js/jquery.gritter.min.js"></script>	
		<script src="js/jquery.imagesloaded.js"></script>	
		<script src="js/jquery.masonry.min.js"></script>	
		<script src="js/jquery.knob.modified.js"></script>	
		<script src="js/jquery.sparkline.min.js"></script>	
		<script src="js/counter.min.js"></script>	
		<script src="js/raphael.2.1.0.min.js"></script>
		<script src="js/justgage.1.0.1.min.js"></script>	
		<script src="js/jquery.autosize.min.js"></script>	
		<script src="js/retina.js"></script>
		<script src="js/jquery.placeholder.min.js"></script>
		<script src="js/wizard.min.js"></script>
		<script src="js/charts.min.js"></script>	
		<script src="js/custom.min.js"></script>
		

		<script src="js/additional.js"></script>
-->

		<script src="js/jquery-1.10.2.min.js"></script>
		<script src="js/jquery-migrate-1.2.1.min.js"></script>	
			<script src="js/jquery-ui-1.10.3.custom.min.js"></script>	
			<script src="js/jquery.ui.touch-punch.js"></script>	
			<script src="js/modernizr.js"></script>	
			<script src="js/bootstrap.min.js"></script>	
			<script src="js/jquery.cookie.js"></script>	
			<script src='js/fullcalendar.min.js'></script>	
			<script src='js/jquery.dataTables.min.js'></script>
			<script src="js/dataTables.tableTools.js"></script>
			
			<script src="js/excanvas.js"></script>
		<script src="js/jquery.flot.js"></script>
		<script src="js/jquery.flot.pie.js"></script>
		<script src="js/jquery.flot.stack.js"></script>
		<script src="js/jquery.flot.resize.min.js"></script>
		<script src="js/jquery.flot.time.js"></script>
		
		<script src="js/jquery.chosen.min.js"></script>	
		<script src="js/jquery.uniform.min.js"></script>		
		<script src="js/jquery.cleditor.min.js"></script>	
		<script src="js/jquery.noty.js"></script>	
		<script src="js/jquery.elfinder.min.js"></script>	
		<script src="js/jquery.raty.min.js"></script>	
		<script src="js/jquery.iphone.toggle.js"></script>	
		<script src="js/jquery.uploadify-3.1.min.js"></script>	
		<script src="js/jquery.gritter.min.js"></script>	
		<script src="js/jquery.imagesloaded.js"></script>	
		<script src="js/jquery.masonry.min.js"></script>	
		<script src="js/jquery.knob.modified.js"></script>	
		<script src="js/jquery.sparkline.min.js"></script>	
		<script src="js/counter.min.js"></script>	
		<script src="js/raphael.2.1.0.min.js"></script>
		<script src="js/justgage.1.0.1.min.js"></script>	
		<script src="js/jquery.autosize.min.js"></script>	
		<script src="js/retina.js"></script>
		<script src="js/jquery.placeholder.min.js"></script>
		<script src="js/wizard.min.js"></script>
		<script src="js/core.min.js"></script>	
		<script src="js/charts.min.js"></script>	
		<script src="js/custom.min.js"></script>
		<script src="js/additional.js"></script>
<?php require("slide_panel.php"); ?>
</body>
<?php
function getProblemType($db,$type){
	$sql="select * from equipment_type where equipment_code='".$type."'";
	$rs=$db->query($sql);

	$nm=$rs->num_rows;
	$row=$rs->fetch_assoc();

	$problem=$row['equipment_name'];
	return $problem;
}
?>